
DROP TABLE department CASCADE CONSTRAINTS;

DROP TABLE employee_list CASCADE CONSTRAINTS;

DROP TABLE employee_secret CASCADE CONSTRAINTS;

DROP TABLE assignment CASCADE CONSTRAINTS;

DROP TABLE time_sheets CASCADE CONSTRAINTS;

DROP SEQUENCE employeeid;

commit;

